In [372]:
#Importing the libraries.
import pandas as pd
import numpy as np
from pandas import read_csv
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [373]:
df = read_csv("train.csv",sep=',',index_col=None)
for col in df:
    #get dtype for column
    dt = df[col].dtype 
    #check if it is a number
    if dt == int or dt == float:
        df[col].fillna(0,inplace=True)
    else:
        df[col].fillna("A",inplace=True)


In [374]:
df.shape

(1460, 81)

In [375]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', 500)
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition  SalePrice
0  1   60          RL       65.0         8450     Pave   A     Reg      Lvl         AllPub    Inside    Gtl       CollgCr      Norm       Norm       1Fam     2Story     7            5            2003       2003          Gable     CompShg  VinylSd     VinylSd     BrkFace    196.0       Gd        TA        PConc      Gd       TA       No           GLQ          706         Unf          0           150        856          GasA    Ex        Y          SBrkr      856       854       0             1710       1             0             2         1         3             1             Gd          8             Typ        0           A           Attchd     2003.0       RFn          2           548         TA         TA         Y          0           61           0              0          0            0         A      A     A           0        2       2008    WD       Normal        208500   
1  2   20          RL       80.0         9600     Pave   A     Reg      Lvl         AllPub    FR2       Gtl       Veenker      Feedr      Norm       1Fam     1Story     6            8            1976       1976          Gable     CompShg  MetalSd     MetalSd     None       0.0         TA        TA        CBlock     Gd       TA       Gd           ALQ          978         Unf          0           284        1262         GasA    Ex        Y          SBrkr      1262      0         0             1262       0             1             2         0         3             1             TA          6             Typ        1           TA          Attchd     1976.0       RFn          2           460         TA         TA         Y          298         0            0              0          0            0         A      A     A           0        5       2007    WD       Normal        181500   
2  3   60          RL       68.0         11250    Pave   A     IR1      Lvl         AllPub    Inside    Gtl       CollgCr      Norm       Norm       1Fam     2Story     7            5            2001       2002          Gable     CompShg  VinylSd     VinylSd     BrkFace    162.0       Gd        TA        PConc      Gd       TA       Mn           GLQ          486         Unf          0           434        920          GasA    Ex        Y          SBrkr      920       866       0             1786       1             0             2         1         3             1             Gd          6             Typ        1           TA          Attchd     2001.0       RFn          2           608         TA         TA         Y          0           42           0              0          0            0         A      A     A           0        9       2008    WD       Normal        223500   
3  4   70          RL       60.0         9550     Pave   A     IR1      Lvl         AllPub    Corner    Gtl       Crawfor      Norm       Norm       1Fam     2Story     7            5            1915       1970          Gable     CompShg  Wd Sdng     Wd Shng     None       0.0         TA        TA        BrkTil     TA       Gd       No           ALQ          216         Unf          0           540        756          G

In [376]:
df = df.drop(['MSZoning','Street','Alley','LandContour','Utilities','LandSlope','Condition1','Condition2','RoofMatl','Heating','BsmtFinType2','BsmtFinSF2','Heating','CentralAir','Electrical','LowQualFinSF','BsmtHalfBath','KitchenAbvGr','Functional','GarageQual','GarageCond','EnclosedPorch','3SsnPorch','ScreenPorch','PoolArea','PoolQC','Fence','MiscFeature','MiscVal','SaleType'],axis=1) 
df.shape

(1460, 52)

In [377]:
df.head(1460)

Id  MSSubClass  LotFrontage  LotArea LotShape LotConfig Neighborhood BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1  BsmtUnfSF  TotalBsmtSF HeatingQC  1stFlrSF  2ndFlrSF  GrLivArea  BsmtFullBath  FullBath  HalfBath  BedroomAbvGr KitchenQual  TotRmsAbvGrd  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea PavedDrive  WoodDeckSF  OpenPorchSF  MoSold  YrSold SaleCondition  SalePrice
0     1     60          65.0         8450     Reg      Inside    CollgCr      1Fam     2Story     7            5            2003       2003          Gable     VinylSd     VinylSd     BrkFace    196.0       Gd        TA        PConc      Gd       TA       No           GLQ          706         150        856          Ex        856       854       1710       1             2         1         3             Gd          8             0           A           Attchd     2003.0       RFn          2           548         Y          0           61           2       2008    Normal        208500   
1     2     20          80.0         9600     Reg      FR2       Veenker      1Fam     1Story     6            8            1976       1976          Gable     MetalSd     MetalSd     None       0.0         TA        TA        CBlock     Gd       TA       Gd           ALQ          978         284        1262         Ex        1262      0         1262       0             2         0         3             TA          6             1           TA          Attchd     1976.0       RFn          2           460         Y          298         0            5       2007    Normal        181500   
2     3     60          68.0         11250    IR1      Inside    CollgCr      1Fam     2Story     7            5            2001       2002          Gable     VinylSd     VinylSd     BrkFace    162.0       Gd        TA        PConc      Gd       TA       Mn           GLQ          486         434        920          Ex        920       866       1786       1             2         1         3             Gd          6             1           TA          Attchd     2001.0       RFn          2           608         Y          0           42           9       2008    Normal        223500   
3     4     70          60.0         9550     IR1      Corner    Crawfor      1Fam     2Story     7            5            1915       1970          Gable     Wd Sdng     Wd Shng     None       0.0         TA        TA        BrkTil     TA       Gd       No           ALQ          216         540        756          Gd        961       756       1717       1             1         0         3             Gd          7             1           Gd          Detchd     1998.0       Unf          3           642         Y          0           35           2       2006    Abnorml       140000   
4     5     60          84.0         14260    IR1      FR2       NoRidge      1Fam     2Story     8            5            2000       2000          Gable     VinylSd     VinylSd     BrkFace    350.0       Gd        TA        PConc      Gd       TA       Av           GLQ          655         490        1145         Ex        1145      1053      2198       1             2         1         4             Gd          9             1           TA          Attchd     2000.0       RFn          3           836         Y          192         84           12      2008    Normal        250000   
5     6     50          85.0         14115    IR1      Inside    Mitchel      1Fam     1.5Fin     5            5            1993       1995          Gable     VinylSd     VinylSd     None       0.0         TA        TA        Wood       Gd       TA       No           GLQ          732         64         796          Ex        796       566       1362       1             1         1         1             TA          5             0           A     

In [378]:
from sklearn.model_selection import train_test_split
# Split-out validation dataset
array = df.values
X = array[:,0:51]
Y = array[:,51]
validation_size = 0.20
seed = 7


In [379]:

encoder = LabelEncoder()
X[:,4] = encoder.fit_transform(X[:,4])
X[:,5] = encoder.fit_transform(X[:,5])
X[:,6] = encoder.fit_transform(X[:,6])
X[:,7] = encoder.fit_transform(X[:,7])
X[:,8] = encoder.fit_transform(X[:,8])
X[:,11] = encoder.fit_transform(X[:,11])
X[:,13] = encoder.fit_transform(X[:,13])
X[:,14] = encoder.fit_transform(X[:,14])
X[:,15] = encoder.fit_transform(X[:,15])
X[:,16] = encoder.fit_transform(X[:,16])
X[:,18] = encoder.fit_transform(X[:,18])
X[:,19] = encoder.fit_transform(X[:,19])
X[:,20] = encoder.fit_transform(X[:,20])
X[:,21] = encoder.fit_transform(X[:,21])
X[:,22] = encoder.fit_transform(X[:,22])
X[:,23] = encoder.fit_transform(X[:,23])
X[:,24] = encoder.fit_transform(X[:,24])
X[:,28] = encoder.fit_transform(X[:,28])
X[:,36] = encoder.fit_transform(X[:,36])
X[:,39] = encoder.fit_transform(X[:,39])
X[:,40] = encoder.fit_transform(X[:,40])
X[:,42] = encoder.fit_transform(X[:,42])
X[:,45] = encoder.fit_transform(X[:,45])
X[:,50] = encoder.fit_transform(X[:,50])
print(X)
print(Y)

[[1 60 65.0 ... 2 2008 4]
 [2 20 80.0 ... 5 2007 4]
 [3 60 68.0 ... 9 2008 4]
 ...
 [1458 70 66.0 ... 5 2010 4]
 [1459 20 68.0 ... 4 2010 4]
 [1460 20 75.0 ... 6 2008 4]]
[208500 181500 223500 ... 266500 142125 147500]


In [380]:
X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y,
test_size=validation_size, random_state=42)

In [381]:
model = LinearRegression()
model.fit(X_train,Y_train)
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [395]:
X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y,
test_size=validation_size, random_state=42)
# Predict on the test data: y_pred
y_pred = model.predict(X_validation)
score = np.mean((Y_validation - y_pred) ** 2)
print(X_validation)
print(y_pred)

[[893 20 70.0 ... 2 2006 4]
 [1106 60 98.0 ... 4 2010 4]
 [414 30 56.0 ... 3 2010 4]
 ...
 [803 60 63.0 ... 10 2008 4]
 [652 70 60.0 ... 10 2009 4]
 [723 20 70.0 ... 7 2009 4]]
[152393.58832002 317518.10689912 112956.84765227 184926.69213919
 331832.72276416  69593.7676509  242804.6560855  137731.60423941
  72618.05117448 134886.94150742 153609.49933503 112149.21019019
  94221.84259472 205676.01187799 173000.46490142 135144.92636087
 216037.41948815 115801.1146413  110998.36869121 229872.26844824
 158172.01323456 211931.11941364 190106.42860274 117859.00315065
 217327.63874258 156114.26136304 209089.39885331  83256.97072438
 170031.07432084 178181.52847832 145656.66839181 263333.46260926
 245135.80969562  97059.21068773 267073.11213654 151500.52946959
 142352.36288233 218027.42279604 293612.69483425 105284.61383451
 130690.53090535 256048.41312687 104050.80081305 312477.55438806
 131873.92025756 143841.27829722  96189.69421494 130887.09763174
 386809.19772899 126344.79184642 106601.603

In [392]:
# Compute and print RMSE, Lower the rmse better the prediction
rmse = np.sqrt(mean_squared_error(Y_validation,y_pred))
print("Root Mean Squared Error: {}".format(rmse))

Root Mean Squared Error: 34052.43528658026
